const CREATE_USER_TABLE_QUERY_KEY = 'CREATE_USER_TABLE_QUERY';
const CREATE_USER_TABLE_QUERY = `CREATE TABLE IF NOT EXISTS user (
  id int unsigned NOT NULL AUTO_INCREMENT,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)`;

module.exports = {
  CREATE_USER_TABLE_QUERY_KEY,
  CREATE_USER_TABLE_QUERY
};
